services:
  - type: web
    name: django-blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd django_blog && gunicorn blogproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog_user
